services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - SERVICE_FQDN_RADARR_7878
      - PUID=1000
      - PGID=1000
      - TZ=Japan
    volumes:
      - /docker/appdata/radarr:/config
      - /data:/data
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:7878/"
      interval: 2s
      timeout: 10s
      retries: 15
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - SERVICE_FQDN_SONARR_8989
      - PUID=1000
      - PGID=1000
      - TZ=Japan
    volumes:
      - /docker/appdata/sonarr:/config
      - /data:/data
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:8989/"
      interval: 2s
      timeout: 10s
      retries: 15
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - SERVICE_FQDN_BAZARR_6767
      - PUID=1000
      - PGID=1000
      - TZ=Japan
    volumes:
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:6767/"
      interval: 2s
      timeout: 10s
      retries: 15
